sys A:

mkdir A:\lanman.dos
mkdir A:\lanman.dos\drivers
mkdir A:\lanman.dos\drivers\ethernet
mkdir A:\lanman.dos\drivers\ethernet\elnk3
mkdir A:\lanman.dos\drivers\protman
mkdir A:\lanman.dos\drivers\protocol
mkdir A:\lanman.dos\drivers\protocol\tcpip
mkdir A:\lanman.dos\drivers\xif
mkdir A:\lanman.dos\etc
mkdir A:\lanman.dos\netprog
mkdir A:\lanman.dos\services

copy CONFIG.SYS A:\CONFIG.SYS
copy AUTOEXEC.BAT A:\AUTOEXEC.BAT
copy LANMAN.DOS\TCPUTILS.INI A:\LANMAN.DOS\TCPUTILS.INI
copy LANMAN.DOS\LANMAN.INI A:\LANMAN.DOS\LANMAN.INI
copy LANMAN.DOS\PROTOCOL.INI A:\LANMAN.DOS\PROTOCOL.INI
copy LANMAN.DOS\LMUSER.INI A:\LANMAN.DOS\LMUSER.INI
copy LANMAN.DOS\DRIVERS\ETHERNET\ELNK3\ELNK3.DOS A:\LANMAN.DOS\DRIVERS\ETHERNET\ELNK3\ELNK3.DOS
copy LANMAN.DOS\DRIVERS\ETHERNET\ELNK3\PROTOCOL.INI A:\LANMAN.DOS\DRIVERS\ETHERNET\ELNK3\PROTOCOL.INI
copy LANMAN.DOS\DRIVERS\PROTMAN\PRO.MSG A:\LANMAN.DOS\DRIVERS\PROTMAN\PRO.MSG
copy LANMAN.DOS\DRIVERS\PROTMAN\PROH.MSG A:\LANMAN.DOS\DRIVERS\PROTMAN\PROH.MSG
copy LANMAN.DOS\DRIVERS\PROTMAN\PROTMAN.DOS A:\LANMAN.DOS\DRIVERS\PROTMAN\PROTMAN.DOS
copy LANMAN.DOS\DRIVERS\PROTMAN\PROTMAN.EXE A:\LANMAN.DOS\DRIVERS\PROTMAN\PROTMAN.EXE
copy LANMAN.DOS\DRIVERS\PROTMAN\PROTCHK.EXE A:\LANMAN.DOS\DRIVERS\PROTMAN\PROTCHK.EXE
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\EMSBFR.EXE A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\EMSBFR.EXE
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\NEMM.DOS A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\NEMM.DOS
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\NMTSR.EXE A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\NMTSR.EXE
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\PROTOCOL.INI A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\PROTOCOL.INI
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\TCPDRV.DOS A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\TCPDRV.DOS
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\TCPTSR.EXE A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\TCPTSR.EXE
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\UNLOADT.EXE A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\UNLOADT.EXE
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\TINYRFC.EXE A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\TINYRFC.EXE
copy LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\UMB.COM A:\LANMAN.DOS\DRIVERS\PROTOCOL\TCPIP\UMB.COM
copy LANMAN.DOS\DRIVERS\XIF\TCPIP.XIF A:\LANMAN.DOS\DRIVERS\XIF\TCPIP.XIF
copy LANMAN.DOS\ETC\NETWORKS A:\LANMAN.DOS\ETC\NETWORKS
copy LANMAN.DOS\ETC\SERVICES A:\LANMAN.DOS\ETC\SERVICES
copy LANMAN.DOS\ETC\PROTOCOLS A:\LANMAN.DOS\ETC\PROTOCOLS
copy LANMAN.DOS\ETC\HOSTS A:\LANMAN.DOS\ETC\HOSTS
copy LANMAN.DOS\ETC\LMHOSTS A:\LANMAN.DOS\ETC\LMHOSTS
copy LANMAN.DOS\NETPROG\DNR.EXE A:\LANMAN.DOS\NETPROG\DNR.EXE
copy LANMAN.DOS\NETPROG\NET.PIF A:\LANMAN.DOS\NETPROG\NET.PIF
copy LANMAN.DOS\NETPROG\NET.MSG A:\LANMAN.DOS\NETPROG\NET.MSG
copy LANMAN.DOS\NETPROG\NET.HLP A:\LANMAN.DOS\NETPROG\NET.HLP
copy LANMAN.DOS\NETPROG\NET.EXE A:\LANMAN.DOS\NETPROG\NET.EXE
copy LANMAN.DOS\NETPROG\MINSES.EXE A:\LANMAN.DOS\NETPROG\MINSES.EXE
copy LANMAN.DOS\NETPROG\NETBIND.COM A:\LANMAN.DOS\NETPROG\NETBIND.COM
copy LANMAN.DOS\NETPROG\LOAD.COM A:\LANMAN.DOS\NETPROG\LOAD.COM
copy LANMAN.DOS\NETPROG\UNLOAD.COM A:\LANMAN.DOS\NETPROG\UNLOAD.COM
copy LANMAN.DOS\NETPROG\CHKNET.EXE A:\LANMAN.DOS\NETPROG\CHKNET.EXE
copy LANMAN.DOS\NETPROG\NETWKSTA.EXE A:\LANMAN.DOS\NETPROG\NETWKSTA.EXE
copy LANMAN.DOS\SERVICES\ENCRYPT.EXE A:\LANMAN.DOS\SERVICES\ENCRYPT.EXE
 
EDIT A:\CONFIG.SYS
EDIT A:\AUTOEXEC.BAT
EDIT A:\LANMAN.DOS\LANMAN.INI
EDIT A:\LANMAN.DOS\PROTOCOL.INI
